version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    hostname: 'satisfactory-server'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
      - '8888:8888/tcp'
    volumes:
      - './config:/config'
    environment:
      - AUTOPAUSE=true
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
    restart: unless-stopped
