version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    hostname: 'satisfactory-server'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - './config:/config'
    environment:
      - AUTOPAUSE=false
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=true
    restart: unless-stopped